-- Activities audit log + organization invitations (org settings, accept-invitation flow)
-- Uses conditional CREATE to avoid NOTICE spam on first deploy (no DROP IF EXISTS).

-- ---------------------------------------------------------------------------
-- organization_invitations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organization_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email text NOT NULL,
  invitation_code text NOT NULL,
  role text NOT NULL DEFAULT 'Customer Relations',
  invited_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  expires_at timestamptz,
  accepted_at timestamptz,
  accepted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT organization_invitations_role_check CHECK (
    role = ANY (ARRAY['Owner'::text, 'Admin'::text, 'Customer Relations'::text, 'Manager'::text])
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS organization_invitations_code_key
  ON public.organization_invitations (invitation_code);

CREATE UNIQUE INDEX IF NOT EXISTS unique_pending_invitation
  ON public.organization_invitations (organization_id, lower(email))
  WHERE accepted_at IS NULL;

CREATE OR REPLACE FUNCTION public.set_organization_invitation_defaults()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.invitation_code IS NULL OR btrim(NEW.invitation_code) = '' THEN
    NEW.invitation_code := encode(gen_random_bytes(16), 'hex');
  END IF;
  NEW.email := lower(btrim(NEW.email));
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger t
    INNER JOIN pg_class c ON c.oid = t.tgrelid
    INNER JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'organization_invitations'
      AND t.tgname = 'organization_invitations_defaults'
      AND NOT t.tgisinternal
  ) THEN
    CREATE TRIGGER organization_invitations_defaults
      BEFORE INSERT OR UPDATE ON public.organization_invitations
      FOR EACH ROW
      EXECUTE FUNCTION public.set_organization_invitation_defaults();
  END IF;
END $$;

ALTER TABLE public.organization_invitations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'organization_invitations'
      AND policyname = 'org_invitations_select'
  ) THEN
    CREATE POLICY "org_invitations_select" ON public.organization_invitations
      FOR SELECT TO authenticated
      USING (
        public.has_any_org_role(organization_id, ARRAY['Owner', 'Admin'])
        OR lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'organization_invitations'
      AND policyname = 'org_invitations_insert'
  ) THEN
    CREATE POLICY "org_invitations_insert" ON public.organization_invitations
      FOR INSERT TO authenticated
      WITH CHECK (
        public.has_any_org_role(organization_id, ARRAY['Owner', 'Admin'])
        AND invited_by = auth.uid()
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'organization_invitations'
      AND policyname = 'org_invitations_update'
  ) THEN
    CREATE POLICY "org_invitations_update" ON public.organization_invitations
      FOR UPDATE TO authenticated
      USING (
        public.has_any_org_role(organization_id, ARRAY['Owner', 'Admin'])
        OR (
          lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
          AND accepted_at IS NULL
        )
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'organization_invitations'
      AND policyname = 'org_invitations_delete'
  ) THEN
    CREATE POLICY "org_invitations_delete" ON public.organization_invitations
      FOR DELETE TO authenticated
      USING (public.has_any_org_role(organization_id, ARRAY['Owner', 'Admin']));
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- activities
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.activities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_name text,
  action_type text NOT NULL,
  entity_type text NOT NULL,
  entity_id bigint,
  description text NOT NULL,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activities_org_created
  ON public.activities (organization_id, created_at DESC);

ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'activities'
      AND policyname = 'activities_select'
  ) THEN
    CREATE POLICY "activities_select" ON public.activities
      FOR SELECT TO authenticated
      USING (public.has_any_org_role(organization_id, ARRAY['Owner', 'Admin']));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'activities'
      AND policyname = 'activities_insert'
  ) THEN
    CREATE POLICY "activities_insert" ON public.activities
      FOR INSERT TO authenticated
      WITH CHECK (
        organization_id IN (
          SELECT organization_id FROM public.organization_members
          WHERE user_id = auth.uid()
        )
        AND user_id = auth.uid()
      );
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Org members: owners/admins can list all members in their org
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'organization_members'
      AND policyname = 'Owners and Admins can view all org members'
  ) THEN
    CREATE POLICY "Owners and Admins can view all org members" ON public.organization_members
      FOR SELECT TO authenticated
      USING (public.has_any_org_role(organization_id, ARRAY['Owner', 'Admin']));
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- accept_organization_invitation RPC
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.accept_organization_invitation(inv_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_inv public.organization_invitations%ROWTYPE;
  v_user_id uuid;
  v_email text;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Not authenticated');
  END IF;

  SELECT lower(email) INTO v_email FROM auth.users WHERE id = v_user_id;
  IF v_email IS NULL OR v_email = '' THEN
    RETURN jsonb_build_object('success', false, 'error', 'User email not found');
  END IF;

  SELECT * INTO v_inv
  FROM public.organization_invitations
  WHERE invitation_code = inv_code
    AND accepted_at IS NULL;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invalid or already used invitation');
  END IF;

  IF v_inv.expires_at IS NOT NULL AND v_inv.expires_at < now() THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invitation has expired');
  END IF;

  IF v_inv.email <> v_email THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invitation was sent to a different email address');
  END IF;

  INSERT INTO public.organization_members (organization_id, user_id, role)
  VALUES (v_inv.organization_id, v_user_id, v_inv.role)
  ON CONFLICT (organization_id, user_id)
  DO UPDATE SET role = EXCLUDED.role, updated_at = now();

  UPDATE public.organization_invitations
  SET accepted_at = now(), accepted_by = v_user_id, updated_at = now()
  WHERE id = v_inv.id;

  RETURN jsonb_build_object(
    'success', true,
    'organization_id', v_inv.organization_id,
    'role', v_inv.role
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.accept_organization_invitation(text) TO authenticated;
